### PR TITLE
Changed README to Markdown syntax

### PR DESCRIPTION
**Pull request by asbjornu**
This PR changes the README file from being plain text to Markdown, which improves readability, usability, search indexing and such when it's hosted here on GitHub.

### CODE REVIEW

**Comment by jflemer-ndp** [comment]
Please submit this upstream:
- https://www.unix-ag.uni-kl.de/~massar/vpnc/
- https://launchpad.net/vpnc

**Comment by asbjornu** [comment]
@jflemer-ndp Thanks for the tip, but I don't even know where to find the README file in any of the URLs you provided me with and have absolutely no clue how to contribute to either website. It's not exactly as straight forward or intuitive as GitHub, I'd say. I'd really appreciate some help.

**Comment by asbjornu** [comment]
I think I figured it out. I've never contributed anything on Launchpad before, but I managed to put [this](https://code.launchpad.net/~asbjorn-ulsberg/vpnc/markdown-readme/+merge/287858) together. I hope it's good enough. Thanks!

**Comment by jflemer-ndp** [comment]
The original source is still using subversion.  Probably just emailing a diff or link to (https://patch-diff.githubusercontent.com/raw/ndpgroup/vpnc/pull/5.patch) to the devel mailing list would work: vpnc-devel@unix-ag.uni-kl.de

**Comment by asbjornu** [comment]
@jflemer-ndp Thanks. I've shipped an e-mail in that direction now, so let's hope the patch will be applied!

**Pull request closed without merging**
